# Generated by Django 5.2.12 on 2026-04-07 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_id', models.CharField(max_length=50, unique=True)),
                ('request_logging', models.BooleanField(default=True)),
                ('debug_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Instance Settings',
                'verbose_name_plural': 'Instance Settings',
            },
        ),
    ]
