# Generated by Django 5.2.13 on 2026-04-09 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_model', models.CharField(blank=True, default='', max_length=200)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=200)),
                ('tts_model', models.CharField(blank=True, default='', max_length=200)),
                ('summarizer_model', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configuration',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🌐', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI-compatible')], default='ollama', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
